version: '3.9'

services:
  node:
    image: node:14
    restart: on-failure
    volumes:
      - ./src:/usr/src/app
    ports:
      - "${NODE_PORT}:80"
      - "9229:9229"
    depends_on:
      - db-mysql
      - db-mongo
    networks:
      - app-network

  db-mysql:
    image: mysql:latest
    restart: on-failure
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      app-network:
        aliases:
          - db-mysql

  phpmyadmin:
    image: phpmyadmin
    restart: on-failure
    environment:
      PMA_HOST: db-mysql
      PMA_PORT: 3306
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - db-mysql
    networks:
      - app-network

  db-mongo:
    image: mongo:latest
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    networks:
      app-network:
        aliases:
          - db-mongo

  mongo-express:
    image: mongo-express
    restart: on-failure
    environment:
      ME_CONFIG_MONGODB_SERVER: db-mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    depends_on:
      - db-mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge